### ISSUE TITLE
Incorrect method names

### ISSUE THREAD

**Issue by edysegura** [dairel/Calculoinssirpf#3]
These method names is not expected for this exam.

![image](https://cloud.githubusercontent.com/assets/5324414/10748018/e7fe2d28-7c42-11e5-89e6-71da80b0e107.png)

**Comment by dairel** [comment]
![getsalary](https://cloud.githubusercontent.com/assets/10948206/10845966/29bee7d6-7ef3-11e5-9855-f39cffede945.PNG)

**Comment by edysegura** [comment]
Much better!!
